name: Refresh

on:
  # schedule:
  #   - cron: '9 * * * *'
  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup environment
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Refresh
      run: python refresh.py
